# -*- coding: utf-8 -*-
"""wk2Widstask1ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1o9ohdNjyhMeI1ltmJCPHkxJXPp80MraD
"""

import cv2
import numpy as np
import matplotlib.pyplot as plt
# Read images
xray = cv2.imread("xray.jpeg")
mri  = cv2.imread("mri.jpg")

# Check if images are loaded successfully
if xray is None:
    raise ValueError("Failed to load xray.jpeg. Please ensure the file exists and is a valid image.")
if mri is None:
    raise ValueError("Failed to load mri.jpg. Please ensure the file exists and is a valid image.")

# Convert from BGR to RGB
xray = cv2.cvtColor(xray, cv2.COLOR_BGR2RGB)
mri  = cv2.cvtColor(mri,  cv2.COLOR_BGR2RGB)

# Display original images
plt.figure(figsize=(8,4))
plt.subplot(1,2,1)
plt.imshow(xray)
plt.title("Original X-ray")
plt.axis("off")

plt.subplot(1,2,2)
plt.imshow(mri)
plt.title("Original MRI")
plt.axis("off")
plt.show()
xray_gray = cv2.cvtColor(xray, cv2.COLOR_RGB2GRAY)
mri_gray  = cv2.cvtColor(mri,  cv2.COLOR_RGB2GRAY)

plt.figure(figsize=(8,4))
plt.subplot(1,2,1)
plt.imshow(xray_gray, cmap='gray')
plt.title("Grayscale X-ray")
plt.axis("off")

plt.subplot(1,2,2)
plt.imshow(mri_gray, cmap='gray')
plt.title("Grayscale MRI")
plt.axis("off")
plt.show()
plt.figure(figsize=(8,4))

plt.subplot(1,2,1)
plt.hist(xray_gray.ravel(), bins=256)
plt.title("X-ray Intensity Histogram")

plt.subplot(1,2,2)
plt.hist(mri_gray.ravel(), bins=256)
plt.title("MRI Intensity Histogram")

plt.show()
target_size = (256, 256)

xray_resized = cv2.resize(xray_gray, target_size)
mri_resized  = cv2.resize(mri_gray,  target_size)

plt.figure(figsize=(8,4))
plt.subplot(1,2,1)
plt.imshow(xray_resized, cmap='gray')
plt.title("Resized X-ray")
plt.axis("off")

plt.subplot(1,2,2)
plt.imshow(mri_resized, cmap='gray')
plt.title("Resized MRI")
plt.axis("off")
plt.show()
xray_edges = cv2.Canny(xray_resized, 100, 200)
mri_edges  = cv2.Canny(mri_resized,  100, 200)

plt.figure(figsize=(8,4))
plt.subplot(1,2,1)
plt.imshow(xray_edges, cmap='gray')
plt.title("X-ray Edges (Canny)")
plt.axis("off")

plt.subplot(1,2,2)
plt.imshow(mri_edges, cmap='gray')
plt.title("MRI Edges (Canny)")
plt.axis("off")
plt.show()
def add_gaussian_noise(image, mean=0, std=20):
    noise = np.random.normal(mean, std, image.shape)
    noisy_image = image + noise
    return np.clip(noisy_image, 0, 255).astype(np.uint8)

xray_noisy = add_gaussian_noise(xray_resized)
mri_noisy  = add_gaussian_noise(mri_resized)

plt.figure(figsize=(8,4))
plt.subplot(1,2,1)
plt.imshow(xray_noisy, cmap='gray')
plt.title("Noisy X-ray")
plt.axis("off")

plt.subplot(1,2,2)
plt.imshow(mri_noisy, cmap='gray')
plt.title("Noisy MRI")
plt.axis("off")
plt.show()
xray_denoised = cv2.GaussianBlur(xray_noisy, (5,5), 0)
mri_denoised  = cv2.GaussianBlur(mri_noisy,  (5,5), 0)

plt.figure(figsize=(8,4))
plt.subplot(1,2,1)
plt.imshow(xray_denoised, cmap='gray')
plt.title("Denoised X-ray")
plt.axis("off")

plt.subplot(1,2,2)
plt.imshow(mri_denoised, cmap='gray')
plt.title("Denoised MRI")
plt.axis("off")
plt.show()

from google.colab import drive
drive.mount('/content/drive')

from google.colab import files

uploaded = files.upload()

for fn in uploaded.keys():
  print(f'User uploaded file "{fn}" with length {len(uploaded[fn])} bytes')

"""After running the cell, a button will appear that says "Choose Files". Click this button to select the files from your local machine that you want to upload. The uploaded files will then be available in the current Colab environment."""